# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Exchange.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(302, 153)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 31, 267, 102))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.source = QtWidgets.QComboBox(self.layoutWidget)
        self.source.setObjectName("source")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.source)
        self.source_value = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.source_value.setObjectName("source_value")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.source_value)
        self.target = QtWidgets.QComboBox(self.layoutWidget)
        self.target.setObjectName("target")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.target)
        self.target_value = QtWidgets.QLineEdit(self.layoutWidget)
        self.target_value.setObjectName("target_value")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.target_value)
        self.convert_button = QtWidgets.QPushButton(self.layoutWidget)
        self.convert_button.setObjectName("convert_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.convert_button)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.convert_button.setText(_translate("Form", "转换"))
